import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, AlertTriangle, Gauge, Leaf, Target, Zap } from 'lucide-react';
import { carbonApi } from '../api/client';
import type { Alert, EmissionRecord, ForecastResponse, KPIResponse, ScopeSummary } from '../types';
import { KpiCard } from './KpiCard';
const colors = ['#00ffb9','#00a6d6','#f59e0b','#ef4444','#8b5cf6'];
export function Dashboard(){
 const [live,setLive]=useState<EmissionRecord[]>([]),[kpis,setKpis]=useState<KPIResponse|null>(null),[trends,setTrends]=useState<any[]>([]),[forecast,setForecast]=useState<ForecastResponse|null>(null),[alerts,setAlerts]=useState<Alert[]>([]),[scopes,setScopes]=useState<ScopeSummary[]>([]);
 useEffect(()=>{Promise.all([carbonApi.live(),carbonApi.kpis(),carbonApi.trends(),carbonApi.forecast(),carbonApi.alerts(),carbonApi.scope(1),carbonApi.scope(2),carbonApi.scope(3)]).then(([l,k,t,f,a,s1,s2,s3])=>{setLive(l);setKpis(k);setTrends(t);setForecast(f);setAlerts(a);setScopes([s1,s2,s3]);}).catch(()=>{});},[]);
 const facilityData=useMemo(()=>Object.entries(live.reduce<Record<string,number>>((acc,r)=>({...acc,[r.facility_name]:(acc[r.facility_name]??0)+r.total_tco2e}),{})).map(([name,value])=>({name,value:Number(value.toFixed(1))})),[live]);
 const scopeData=scopes.map(s=>({name:s.scope,value:s.total_tco2e}));
 return <main className="min-h-screen flex-1 overflow-hidden bg-[radial-gradient(circle_at_top_right,rgba(0,255,185,.14),transparent_34%),linear-gradient(180deg,#07111f,#0b1729)] p-4 md:p-8"><header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm uppercase tracking-[.35em] text-siemens-cyan">Siemens-inspired sustainability command center</p><h1 className="mt-3 text-4xl font-bold text-white">Industrial Carbon Intelligence Platform</h1><p className="mt-2 max-w-3xl text-slate-400">Scope 1/2/3 tracking, AI forecasting, anomaly detection, renewable optimization, and multi-facility ESG intelligence for manufacturing and energy operations.</p></div><div className="rounded-2xl border border-cyan-300/20 px-4 py-3 text-sm text-slate-300 shadow-glow">Live plant telemetry simulator</div></header>
 {kpis&&<section className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-5"><KpiCard title="Total footprint" value={`${Math.round(kpis.total_emissions_tco2e).toLocaleString()} t`} detail="Gross Scope 1+2+3 CO₂e" icon={Activity}/><KpiCard title="Renewable share" value={`${kpis.renewable_share_pct}%`} detail="Intermittent solar/wind contribution" icon={Leaf}/><KpiCard title="Carbon intensity" value={kpis.carbon_intensity_tco2e_per_ton.toFixed(3)} detail="tCO₂e per production ton" icon={Gauge}/><KpiCard title="Net-zero progress" value={`${kpis.net_zero_progress_pct}%`} detail="Against simulated baseline" icon={Target}/><KpiCard title="Active alerts" value={`${alerts.length}`} detail="Spikes, inefficiency, regressions" icon={AlertTriangle} accent="text-amber-400"/></section>}
 <section className="mt-6 grid gap-6 xl:grid-cols-3"><Panel title="Real-time emissions trend" wide><ResponsiveContainer height={310}><AreaChart data={trends}><defs><linearGradient id="co2" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#00ffb9" stopOpacity={0.5}/><stop offset="95%" stopColor="#00ffb9" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#33415555"/><XAxis dataKey="date" hide/><YAxis/><Tooltip/><Legend/><Area type="monotone" dataKey="total_tco2e" stroke="#00ffb9" fill="url(#co2)" name="Total tCO₂e"/><Line type="monotone" dataKey="renewable_share_pct" stroke="#38bdf8" name="Renewable %"/></AreaChart></ResponsiveContainer></Panel><Panel title="Scope portfolio"><ResponsiveContainer height={310}><PieChart><Pie data={scopeData} dataKey="value" nameKey="name" innerRadius={70} outerRadius={105}>{scopeData.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></Panel></section>
 <section className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="Facility emissions comparison"><ResponsiveContainer height={320}><BarChart data={facilityData}><CartesianGrid stroke="#33415555"/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis/><Tooltip/><Bar dataKey="value" radius={[8,8,0,0]}>{facilityData.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Bar></BarChart></ResponsiveContainer></Panel><Panel title="AI emissions forecast"><ResponsiveContainer height={320}><LineChart data={forecast?.forecast ?? []}><CartesianGrid stroke="#33415555"/><XAxis dataKey="date" hide/><YAxis/><Tooltip/><Legend/><Line type="monotone" dataKey="predicted_emissions_tco2e" stroke="#00ffb9" strokeWidth={2}/><Line type="monotone" dataKey="predicted_energy_kwh" stroke="#38bdf8" strokeWidth={2} yAxisId={0}/></LineChart></ResponsiveContainer><p className="text-xs text-slate-400">Model evaluation: MAE {forecast?.mae ?? 'training'} / RMSE {forecast?.rmse ?? 'training'}</p></Panel></section>
 <section className="mt-6 grid gap-6 xl:grid-cols-3"><Panel title="Alert stream" wide>{alerts.slice(0,6).map(a=><div key={`${a.date}-${a.facility_id}-${a.category}`} className="mb-3 rounded-xl border border-white/10 bg-white/5 p-3"><div className="flex items-center justify-between text-sm"><span className={a.severity==='critical'?'text-red-300':'text-amber-300'}>{a.category}</span><span className="text-slate-500">{a.date}</span></div><p className="mt-1 text-sm text-slate-300">{a.message}</p><p className="mt-1 text-xs text-slate-500">{a.facility_id} observed {a.observed_value}, baseline {a.baseline_value}</p></div>)}</Panel><Panel title="Renewable energy tracking"><ResponsiveContainer height={250}><AreaChart data={trends}><XAxis dataKey="date" hide/><YAxis/><Tooltip/><Area type="monotone" dataKey="renewable_kwh" stroke="#00ffb9" fill="#00ffb933"/><Area type="monotone" dataKey="electricity_kwh" stroke="#38bdf8" fill="#38bdf822"/></AreaChart></ResponsiveContainer></Panel></section></main>;
}
function Panel({title,children,wide=false}:{title:string;children:ReactNode;wide?:boolean}){return <div className={`glass rounded-3xl p-5 ${wide?'xl:col-span-2':''}`}><div className="mb-4 flex items-center gap-2 text-white"><Zap className="h-4 w-4 text-siemens-cyan"/><h2 className="font-semibold">{title}</h2></div>{children}</div>}
